#!/usr/bin/env npx tsx
/**
 * Regenerate docs/AGENT_BUILDER_V1_SPEC.md Section 3 ("Agent User Prompt") from the
 * canonical source in `src/agent-builder/agent-prompt.ts`. This keeps the spec
 * doc and the provisioned agent byte-identical (verifiable via `diff`).
 *
 * Usage:
 *   npm run gen:spec        # regenerate
 *   npm run gen:spec -- --check   # exit 1 if spec is out of sync
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { AGENT_USER_PROMPT } from '../src/agent-builder/agent-prompt.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const SPEC_PATH = resolve(__dirname, '..', 'docs', 'AGENT_BUILDER_V1_SPEC.md');

const SECTION_START_MARKER = '<!-- AUTO-GEN:AGENT_PROMPT START -->';
const SECTION_END_MARKER = '<!-- AUTO-GEN:AGENT_PROMPT END -->';

function generatedBlock(): string {
  return `${SECTION_START_MARKER}
<!--
  This block is auto-generated by \`npm run gen:spec\`.
  Source of truth: src/agent-builder/agent-prompt.ts (composed from per-rule
  agentPromptSnippet fields). Do NOT edit by hand.
-->

\`\`\`text
${AGENT_USER_PROMPT}
\`\`\`

${SECTION_END_MARKER}`;
}

function syncSpec(check: boolean): void {
  const existing = readFileSync(SPEC_PATH, 'utf-8');
  const startIdx = existing.indexOf(SECTION_START_MARKER);
  const endIdx = existing.indexOf(SECTION_END_MARKER);

  let updated: string;
  if (startIdx === -1 || endIdx === -1) {
    // First time — append the block at the end.
    updated = `${existing.trimEnd()}\n\n## 3. Agent User Prompt (auto-generated)\n\n${generatedBlock()}\n`;
  } else {
    const before = existing.substring(0, startIdx);
    const after = existing.substring(endIdx + SECTION_END_MARKER.length);
    updated = `${before}${generatedBlock()}${after}`;
  }

  if (existing === updated) {
    console.log('docs/AGENT_BUILDER_V1_SPEC.md already in sync.');
    return;
  }

  if (check) {
    console.error(
      'docs/AGENT_BUILDER_V1_SPEC.md is OUT OF SYNC with src/agent-builder/agent-prompt.ts.\n' +
        'Run `npm run gen:spec` to update, then commit.',
    );
    process.exit(1);
  }

  writeFileSync(SPEC_PATH, updated, 'utf-8');
  console.log(
    `Updated docs/AGENT_BUILDER_V1_SPEC.md (prompt length: ${AGENT_USER_PROMPT.length} chars).`,
  );
}

const checkMode = process.argv.includes('--check');
syncSpec(checkMode);
